In [1]:
my_list = [1,2,3]

In [2]:
print(my_list)

[1, 2, 3]


In [3]:
import numpy as np

In [4]:
my_list_2 = my_list

In [5]:
my_matrix = [my_list,my_list_2]

In [6]:
my_matrix

[[1, 2, 3], [1, 2, 3]]

In [12]:
type(my_matrix)

numpy.ndarray

Converting list to n dimensional array

In [11]:
my_matrix = np.array(my_matrix)

In [10]:
type(my_matrix)

numpy.ndarray

To create a matrix with 0's

In [13]:
zero_matrix = np.zeros((5,5))

In [14]:
zero_matrix

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

To create a matrix with 1's

In [15]:
one_matrix = np.ones((3,3))

In [16]:
one_matrix

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

To create identity matrix

In [17]:
identity_matrix = np.eye(4)

In [18]:
identity_matrix

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

To create uniform distributed (0-1) random numbers

In [20]:
np.random.rand(5)

array([ 0.2794804 ,  0.17728849,  0.65142191,  0.50333543,  0.50809911])

To create normal distributed random numbers

In [23]:
random_normal = np.random.rand(5,5)

To create random integer

In [22]:
np.random.randint(1,100)

68

To gather the max value from an array

In [24]:
random_normal.max()

0.91280127612481321

To gather the min value of an array

In [25]:
random_normal.min()

0.045696939875108478

To gather the location of max and min values

In [30]:
random_normal.argmax()

11

In [31]:
random_normal.argmin()

19

To gather the data type of an array

In [33]:
random_normal.dtype

dtype('float64')

In [34]:
type(random_normal)

numpy.ndarray