In [2]:
#Loading library
import numpy as np
import pandas as pd

### Series

In [3]:
#Pandas has "series" and "data frame" objects. Data frames are created via series.
series_object = pd.Series([10,20,30])
print(series_object)
print('')
print(type(series_object))

0    10
1    20
2    30
dtype: int64

<class 'pandas.core.series.Series'>


In [8]:
#Series has value and index
print('Printing values: ',series_object.values)
print('Printing indexes: ',series_object.index)

Printing values:  [10 20 30]
Printing indexes:  RangeIndex(start=0, stop=3, step=1)


In [17]:
#Series slicing - 1:
series_object.loc[0]

10

In [18]:
#Series slicing - 2:
series_object.loc[1:]

1    20
2    30
dtype: int64

In [21]:
#Calling series object with index value. As seen index values does not have to be in order or numeric or string.
series_object_with_index = pd.Series([10,20,30],index=[1000,25000,'a'])
print(series_object_with_index['a'])

30


### DataFrame

In [66]:
#Creating data frame via series objects 
x = pd.Series({'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5})
y = pd.Series({'A': 6, 'B': 7, 'C': 8, 'D': 9, 'E': 10})
df = pd.DataFrame({'C1':x, 'C2':y})
print(df)

   C1  C2
A   1   6
B   2   7
C   3   8
D   4   9
E   5  10


In [ ]:
#To gather column names of dataframe
list(df)

In [ ]:
#Row number in dataframe
df.count()

In [69]:
#Data Frame Slicing - 1: Slicing first column of data frame
df['C1']

A    1
B    2
C    3
D    4
E    5
Name: C1, dtype: int64

In [71]:
#Data Frame Slicing - 2: Slicing first row of data frame
df.values[0]

array([1, 6])

In [72]:
#Data Frame Slicing - 3: First 3 rows and 2 columns or slicing row index up to 3 and column index up to 2
#iloc is used for position indexing
data.iloc[:3, :2]

area  pop
A     1    6
B     2    7
C     3    8

In [75]:
#Data Frame Slicing - 4: Label index including up to C and columns up to C2
#loc is used for label indexing
df.loc[:'C', :'C2']

C1  C2
A   1   6
B   2   7
C   3   8

In [76]:
#Data Frame Slicing - 5: Conditional slicing
df[df['C1']>2]['C2']

C     8
D     9
E    10
Name: C2, dtype: int64

In [81]:
#Data Frame Slicing - 6: Complex conditional slicing
df[((df['C1']>2) & (df['C1']<10)) | ((df['C1'] < 2) & (df['C2'] > 100))]['C2']

C     8
D     9
E    10
Name: C2, dtype: int64

In [85]:
#Data Frame Slicing - 7: Label based indexing
df['A':'C']

C1  C2
A   1   6
B   2   7
C   3   8

In [86]:
#Data Frame Slicing - 8: Label based indexing
df.loc['A':'C']

C1  C2
A   1   6
B   2   7
C   3   8

In [83]:
#Data Frame Slicing - 9: Position based indexing
df[0:3]

C1  C2
A   1   6
B   2   7
C   3   8

In [84]:
#Data Frame Slicing - 10: Position based indexing
df.iloc[0:3]

C1  C2
A   1   6
B   2   7
C   3   8

In [92]:
#Operations with Data Frames
print('Multiplying data frame')
print(np.multiply(df,2))
print('\nLets check type of the result\n')
type(np.multiply(df,2))
print('Subtracting from data frame')
print(np.subtract(df,2))

Multiplying data frame
   C1  C2
A   2  12
B   4  14
C   6  16
D   8  18
E  10  20

Lets check type of the result

Subtracting from data frame
   C1  C2
A  -1   4
B   0   5
C   1   6
D   2   7
E   3   8


### Missing Data in DataFrame

In [105]:
#Missing Data Dilemma
#I am copying data frame in order to not change existing one and updating new one
df_missing = df.copy()
df_missing.iloc[0] = np.nan
print(df_missing)
print(df)

    C1    C2
A  NaN   NaN
B  2.0   7.0
C  3.0   8.0
D  4.0   9.0
E  5.0  10.0
   C1  C2
A   1   6
B   2   7
C   3   8
D   4   9
E   5  10


In [113]:
#Checking missing data
df_missing.isnull()

C1     C2
A   True   True
B  False  False
C  False  False
D  False  False
E  False  False

In [116]:
#Sum of elements
print('Sum of elements:\n',np.nansum(df))
print('Sum of non missing elements:\n',np.nansum(df_missing))

Sum of elements:
 55
Sum of non missing elements:
 48.0


In [130]:
#Deleting missing rows
df_missing.dropna()

C1    C2
B  2.0   7.0
C  3.0   8.0
D  4.0   9.0
E  5.0  10.0

In [132]:
#Filling missing data
df_missing.fillna(99)

C1    C2
A  99.0  99.0
B   2.0   7.0
C   3.0   8.0
D   4.0   9.0
E   5.0  10.0

### Concat in DataFrame

In [134]:
#Creating arrays
A = [1,2,3]
B = [4,5,6]
print(np.concatenate([A,B]))

[1 2 3 4 5 6]


In [149]:
#Creating series
X = pd.Series([1,2,3],index=['A','B','C'])
Y = pd.Series([4,5,6],index=['A','B','C'])
print('Numpy concat:\n')
print(np.concatenate([X,Y]))
print('\n')
print(type(np.concatenate([X,Y])))
print('\n')
print('Pandas concat:\n')
print(pd.concat([X,Y]))
print('\n')
print(type(pd.concat([X,Y])))
print('\n')

Numpy concat:

[1 2 3 4 5 6]


<class 'numpy.ndarray'>


Pandas concat:

A    1
B    2
C    3
A    4
B    5
C    6
dtype: int64


<class 'pandas.core.series.Series'>




In [151]:
#Creating data frame
df = pd.DataFrame({'C1':X, 'C2':Y})
print(df)
print(type(df))

   C1  C2
A   1   4
B   2   5
C   3   6
<class 'pandas.core.frame.DataFrame'>


In [155]:
#Creating new data frames via old one
print('Same of the old one\n')
df_1 = df.copy()
print(df_1,'\n')
print('Multiplying the old one with 2\n')
df_2 = (df*2).copy()
print(df_2,'\n')

Same of the old one

   C1  C2
A   1   4
B   2   5
C   3   6 

Multiplying the old one with 2

   C1  C2
A   2   8
B   4  10
C   6  12 



In [159]:
#Appending DataFrames - 1: Same size and label
#Here concat is inserting second dataframe to first dataframes. This is default behaviour of pandas concat
print(pd.concat([df_1, df_2]))

   C1  C2
A   1   4
B   2   5
C   3   6
A   2   8
B   4  10
C   6  12


In [161]:
#Appending DataFrames - 2: Same size and label
#We can change inserting behaviour. Default axis=0 which is row. We changed it to axis=2
print(pd.concat([df_1, df_2],axis=1))

   C1  C2  C1  C2
A   1   4   2   8
B   2   5   4  10
C   3   6   6  12


In [166]:
#Appending DataFrames - 3: Indexing problem
#For row concat there becomes a repeating index problem
print('Original concat\n')
print(pd.concat([df_1, df_2]))
print('')
#In order to solve this problem we must ignore original indexes
print('Concat with ignoring index')
print(pd.concat([df_1, df_2], ignore_index=True))
print('')

Original concat

   C1  C2
A   1   4
B   2   5
C   3   6
A   2   8
B   4  10
C   6  12

Concat with ignoring index
   C1  C2
0   1   4
1   2   5
2   3   6
3   2   8
4   4  10
5   6  12



### Join and Merge in DataFrame

In [182]:
#Join and Merge in DataFrame - 1:
#Changing column names for join
df_2.columns = ['C3','C4']
print('New df_2:',df_2)
print('')
print('Original concat produces NaN values because of different columns\n')
print(pd.concat([df_1, df_2]))
print('')
print('Using default join:')
print('')
print(pd.concat([df_1, df_2],join='outer'))
print('')
print('Default join is outer as seen above')

New df_2:    C3  C4
A   2   8
B   4  10
C   6  12

Original concat produces NaN values because of different columns

    C1   C2   C3    C4
A  1.0  4.0  NaN   NaN
B  2.0  5.0  NaN   NaN
C  3.0  6.0  NaN   NaN
A  NaN  NaN  2.0   8.0
B  NaN  NaN  4.0  10.0
C  NaN  NaN  6.0  12.0

Using default join:

    C1   C2   C3    C4
A  1.0  4.0  NaN   NaN
B  2.0  5.0  NaN   NaN
C  3.0  6.0  NaN   NaN
A  NaN  NaN  2.0   8.0
B  NaN  NaN  4.0  10.0
C  NaN  NaN  6.0  12.0

Default join is outer as seen above


In [191]:
#Join and Merge in DataFrame - 2:
#Creating efficient data set for join
df_personel_group = pd.DataFrame({'personel': ['A', 'B', 'C', 'D'],
                                  'department': ['X', 'Y', 'Y', 'Z']})
df_personel_age = pd.DataFrame({'personel': ['A', 'B', 'C', 'D'],'age': [40, 20, 30, 60]})

In [187]:
#Displaying DataFrames
print(df_personel_group)
print(df_personel_age)

  department personel
0          X        A
1          Y        B
2          Y        C
3          Z        D
   age personel
0   40        A
1   20        B
2   30        C
3   60        D


In [188]:
#Merging DataFrames using inner join on key column(One-toone)
pd.merge(df_personel_group,df_personel_age,how='inner',on='personel')

department personel  age
0          X        A   40
1          Y        B   20
2          Y        C   30
3          Z        D   60

In [205]:
#Join and Merge in DataFrame - 3:
#Adding rows to df_personel_age
df_new_personel = pd.DataFrame({'personel':['E','F','G'],'age':[40,25,30]})
df_personel_age = pd.concat([df_personel_age, df_new_personel], ignore_index=True)

In [212]:
#One to Many Joins
print(pd.merge(df_personel_group,df_personel_age,how='inner',on='personel'))
print(pd.merge(df_personel_age,df_personel_group,how='inner',on='personel'))
print(pd.merge(df_personel_age,df_personel_group,how='outer',on='personel'))
print(pd.merge(df_personel_age,df_personel_group,how='outer',left_on='personel',right_on='personel'))

  department personel  age
0          X        A   40
1          Y        B   20
2          Y        C   30
3          Z        D   60
   age personel department
0   40        A          X
1   20        B          Y
2   30        C          Y
3   60        D          Z
   age personel department
0   40        A          X
1   20        B          Y
2   30        C          Y
3   60        D          Z
4   40        E        NaN
5   25        F        NaN
6   30        G        NaN
   age personel department
0   40        A          X
1   20        B          Y
2   30        C          Y
3   60        D          Z
4   40        E        NaN
5   25        F        NaN
6   30        G        NaN


### Aggregation and Grouping

In [3]:
#Gathering Data
credit = pd.read_csv(r"/home/seckindinc/Desktop/Github/Python/Data-Sets/Risk.txt",sep=",",index_col=False)

In [215]:
#First couple rows
credit.head()

ID  AGE  INCOME GENDER    MARITAL  NUMKIDS  NUMCARDS  HOWPAID MORTGAGE  \
0  100756   44   59944      m  married          1         2  monthly        y   
1  100668   35   59692      m  married          1         1  monthly        y   
2  100418   34   59508      m  married          1         1  monthly        y   
3  100416   34   59463      m  married          0         2  monthly        y   
4  100590   39   59393      f  married          0         2  monthly        y   

   STORECAR  LOANS        RISK  
0         2      0  good risk   
1         1      0  bad loss    
2         2      1  good risk   
3         1      1  bad loss    
4         1      0  good risk

In [220]:
#Aggregate -1: Basics
print('Sum of Age column:\n',credit['AGE'].sum())
print('Average of Age column:\n',credit['AGE'].mean())

Sum of Age column:
 131001
Average of Age column:
 31.819528783094487


In [240]:
#Aggregate -2: Descriptive Statistics
credit.groupby('MORTGAGE')['AGE'].describe().unstack()

       MORTGAGE
count  n            917.000000
       y           3200.000000
mean   n             33.593239
       y             31.311250
std    n             10.477845
       y              9.639322
min    n             20.000000
       y             18.000000
25%    n             23.000000
       y             22.000000
50%    n             33.000000
       y             30.000000
75%    n             44.000000
       y             40.000000
max    n             50.000000
       y             50.000000
dtype: float64

In [237]:
#Aggregate -3: Group bying based on a column and counting another column
print('AGE non null row counts based on MORTAGAGE class,',credit.groupby('MORTGAGE')['AGE'].count())
print('')
print('AGE non null medians based on MORTAGAGE class,',credit.groupby('MORTGAGE')['AGE'].median())

AGE non null row counts based on MORTAGAGE class, MORTGAGE
n     917
y    3200
Name: AGE, dtype: int64

AGE non null medians based on MORTAGAGE class, MORTGAGE
n    33
y    30
Name: AGE, dtype: int64


In [266]:
#Aggregate
credit.groupby('MORTGAGE')['AGE','INCOME'].aggregate(['min', np.median, max])

AGE            INCOME                
         min median max    min   median    max
MORTGAGE                                      
n         20     33  50  15046  22918.0  29986
y         18     30  50  15005  23645.5  59944

In [268]:
#Transformation
credit.groupby('MORTGAGE')['AGE'].transform(lambda x: x - x.mean())

0       12.688750
1        3.688750
2        2.688750
3        2.688750
4        7.688750
5        9.688750
6       10.688750
7       -0.311250
8       -3.311250
9       -1.311250
10       6.688750
11       4.688750
12      10.688750
13      12.688750
14       1.688750
15      13.688750
16       2.688750
17       0.688750
18       3.688750
19       6.688750
20      -3.311250
21      11.688750
22       9.688750
23      11.688750
24      12.688750
25       5.688750
26       2.688750
27       1.688750
28       6.688750
29       7.688750
          ...    
4087    -7.311250
4088     7.406761
4089    -4.311250
4090   -12.593239
4091    -3.593239
4092   -12.311250
4093   -10.311250
4094    -7.311250
4095    11.688750
4096     6.406761
4097     3.406761
4098   -11.593239
4099    12.406761
4100    -4.311250
4101   -11.311250
4102   -10.311250
4103   -10.311250
4104    14.406761
4105    -5.593239
4106     4.688750
4107   -12.593239
4108    -6.311250
4109   -10.311250
4110     7.406761
4111    -7

In [270]:
#Pivot Tables default creates mean
credit.pivot_table('AGE', index='MORTGAGE', columns='HOWPAID')

HOWPAID     monthly    weekly 
MORTGAGE                      
n         24.460581  36.849112
y         31.092997  31.586572

In [4]:
#Higher Dimensions Pivot Tables default creates mean
credit.pivot_table('AGE', index=['MORTGAGE','MARITAL'], columns='HOWPAID', aggfunc='mean')

HOWPAID               monthly    weekly 
MORTGAGE MARITAL                        
n        divsepwid        NaN  42.440171
         single     24.460581  24.269231
y        divsepwid        NaN  42.666667
         married    31.518490  28.006321
         single     29.958932  24.027397

### String Operations

In [7]:
#Creating string array
string_array = ['seckin','elif','kofte','dinc']

In [20]:
#Capitalizing every element
string_array = [s.capitalize() for s in string_array]

In [22]:
#Converting from array to pandas series object
string_array = pd.Series(string_array)

In [23]:
#Checking type
type(string_array)

pandas.core.series.Series

In [26]:
#Printing elements with no space concat
string_array.str.cat()

'SeckinElifKofteDinc'

In [27]:
#Searching string for a pattern and returning Bool
string_array.str.contains('Kof')

0    False
1    False
2     True
3    False
dtype: bool

In [30]:
#Lpad and Rpad at the same time with centralizing element
string_array.str.center(20,'0')

0    0000000Seckin0000000
1    00000000Elif00000000
2    0000000Kofte00000000
3    00000000Dinc00000000
dtype: object

In [35]:
#Return lowest indexes in each strings in the Series/Index where the substring is fully contained between
string_array.str.find('te')

0   -1
1   -1
2    3
3   -1
dtype: int64

In [32]:
#Length of each element in the series object
string_array.str.len()

0    6
1    4
2    5
3    4
dtype: int64