In [1]:
#Importing numpy library
import numpy as np

In [33]:
#Creating list with range function 10 to 19
l = np.array(range(10,20))

In [34]:
#Gathering type of l object
type(l)

numpy.ndarray

In [35]:
#Printing numpy array
l

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
#Creating an array starting from 10 and ending at 20 with increase 2
l = np.arange(10,20,2)
print(l)

In [27]:
#Creating uniform distributed random numbers in a range of 0 and 1
np.random.random(10)

array([ 0.54170071,  0.54793309,  0.951899  ,  0.22961499,  0.77277172,
        0.47822385,  0.33367987,  0.00290045,  0.69089024,  0.00597091])

In [30]:
#Creating normal distributed random numbers in a mean of 0 and std of 1
np.random.normal(0,1,10)

array([-0.40324481,  0.91848779,  2.69826946, -0.41807943, -0.68098432,
        1.15425003, -0.56898406, -1.17981523, -0.32395421,  0.37111409])

In [31]:
#Creating random numbers in a range of 0 - 10
np.random.randint(0,100,10)

array([54, 15, 28,  6, 25, 41, 27, 48, 92, 41])

In [32]:
#Random seed
np.random.seed(seed=101)

In [36]:
#Array slicing - 1: Gathering values index starting position from 0 to 3
l[0:4]

array([10, 11, 12, 13])

In [39]:
#Array slicing - 2: Gathering values index starting position from 4 to the end
l[4:]

array([14, 15, 16, 17, 18, 19])

In [40]:
#Array slicing - 3: Gathering values from start to the end except the last one
l[:-1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [43]:
#Array slicing - 4: Gathering values from start index to the end by increment 2
l[::2]

array([10, 12, 14, 16, 18])

In [46]:
#Array slicing - 5: Gathering values from start index to the end by increment 2(Same of the above)
l[0::2]

array([10, 12, 14, 16, 18])

In [48]:
#Array slicing - 6: Gathering values from start index 1 to the end by increment 2(Same of the above)
l[1::2]

array([11, 13, 15, 17, 19])

In [56]:
#Creating 4*4 dimension array
l2 = np.random.randint(1,15, size=(4, 4))
print (l2)

[[ 3  8  8  8]
 [13  1  5 11]
 [13  2  9 12]
 [ 4  2 14  9]]


In [57]:
#Array slicing - 7: Gathering values from row index starting from 1 to end for each column
l2[1:]

array([[13,  1,  5, 11],
       [13,  2,  9, 12],
       [ 4,  2, 14,  9]])

In [58]:
#Array slicing - 8: Gathering values from column index ending at 1 for each row
l2[:1]

array([[3, 8, 8, 8]])

In [62]:
#Array slicing - 9: Gathering values row index up to 2 and column index up to 3
l2[:2, :3]

array([[ 3,  8,  8],
       [13,  1,  5]])

In [67]:
#Array slicing - 10: Gathering first column
l2[:,0]

array([ 3, 13, 13,  4])

In [68]:
#Array slicing - 11: Gathering first row
l2[0,:]

array([3, 8, 8, 8])

In [74]:
#Arithmetic operations with arrays
print(l)
print("Adding 2 to every element")
print(np.add(l,2))
print("Subtracting 2 from every element")
print(np.subtract(l,2))
print("Multiplying every element with 2")
print(np.multiply(l,2))
print(l)

[10 11 12 13 14 15 16 17 18 19]
[12 13 14 15 16 17 18 19 20 21]
[ 8  9 10 11 12 13 14 15 16 17]
[20 22 24 26 28 30 32 34 36 38]
[10 11 12 13 14 15 16 17 18 19]


In [76]:
#Sum function 1d array
print(l.sum())

145


In [77]:
#Min function 1d array 
print(l.min())

10


In [78]:
#Max function 1d array
print(l.max())

19


In [79]:
#Sum function m*n d array
print(l2.sum())

122


In [81]:
#Min function m*n d array
print(l2.min())

1


In [82]:
#Max function m*n d array
print(l2.max())

14


In [83]:
#Min function in columns
print(l2.min(axis=0))

[3 1 5 8]


In [87]:
#Min function in rows
print(l2.min(axis=1))

[3 1 2 2]


In [93]:
#Logical Operations
b = l > 15
print (b)

[False False False False False False  True  True  True  True]


In [94]:
#Counting non zero elements of array
np.count_nonzero(l)

10

In [102]:
#Number of elements whose values are greather then 15 and under 19
print(np.sum((l > 15) & (l < 19)))

3


In [109]:
#Sorting array n*m dim array
print(l2)
print ('')
print(np.sort(l2))

[[ 3  8  8  8]
 [13  1  5 11]
 [13  2  9 12]
 [ 4  2 14  9]]

[[ 3  8  8  8]
 [ 1  5 11 13]
 [ 2  9 12 13]
 [ 2  4  9 14]]
